# Generated by Django 5.0.6 on 2024-07-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('types_of_visa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryToTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_stay', models.CharField(max_length=20)),
                ('notes', models.TextField(max_length=300)),
                ('country_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_from', to='countries.country')),
                ('country_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_to', to='countries.country')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='types_of_visa.visa')),
            ],
        ),
    ]
