# Generated by Django 5.0.6 on 2024-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_to_travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytotravel',
            name='allowed_stay',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
