# Generated by Django 5.0.6 on 2024-07-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_to_travel', '0002_alter_countrytotravel_allowed_stay'),
        ('types_of_visa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrytotravel',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='countrytotravel',
            name='visa_type',
            field=models.ManyToManyField(blank=True, related_name='visa', to='types_of_visa.visa'),
        ),
    ]
