# Generated by Django 5.0.6 on 2024-07-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('country_to_travel', '0003_remove_countrytotravel_visa_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrytotravel',
            unique_together={('country_from', 'country_to')},
        ),
    ]
