# Generated by Django 5.0.6 on 2024-07-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_to_travel', '0004_alter_countrytotravel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytotravel',
            name='allowed_stay',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
