# Generated by Django 5.0.6 on 2024-07-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_to_travel', '0005_alter_countrytotravel_allowed_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytotravel',
            name='allowed_stay',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
