# Generated by Django 5.0.6 on 2024-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
